name = "SqrtDirichlet"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["SqrtDirichlet"]
authors = ["Alok Singh"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = true
relaxedAutoImplicit = false
linter.missingDocs = true

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "SqrtDirichlet"
